server:
  shutdown: graceful

spring:
  application:
    name: authentication-api
  profiles:
    active: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s


  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"
    aes:
      secret: "YourSecretKeyKey"


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
